name: 'prod deployment'
on:
  push:
    branches: master
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm install

      - name: build
        run: npm run build

        # tested to be added 
      - name: deploy
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
